import { Profile, Gig, Review } from './types.ts';

export const MOCK_PROFILES: Omit<Profile, 'reviews' | 'averageRating'>[] = [
  // Models
  {
    id: '1',
    userId: 'user1',
    name: 'Elara Vance',
    role: 'Model',
    bio: 'A visionary model with a passion for avant-garde fashion and timeless photography. Seeking to collaborate with creatives who push boundaries.',
    profilePictureUrl: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?q=80&w=600&h=800&auto=format&fit=crop',
    contactInfo: { email: 'elara@test.com', website: 'galleryoflight.dev/elara' },
    height: "5'10\"",
    weight: "125 lbs",
    eyeColor: "Hazel",
    hairColor: "Brunette",
    portfolio: [
      { id: 'p1', url: 'https://images.unsplash.com/photo-1581338834612-24136444553c?q=80&w=800&h=1200&auto=format&fit=crop', caption: 'Desert sun.' },
      { id: 'p2', url: 'https://images.unsplash.com/photo-1542328522-8DEF03B19484?q=80&w=800&h=1200&auto=format&fit=crop', caption: 'Urban elegance.' },
      { id: 'p3', url: 'https://images.unsplash.com/photo-1533613603411-28b9a1c6c596?q=80&w=800&h=1200&auto=format&fit=crop', caption: 'Monochrome mood.' },
      { id: 'p4', url: 'https://images.unsplash.com/photo-1589465885857-add69b15c57a?q=80&w=800&h=1200&auto=format&fit=crop', caption: 'Golden hour glow.' },
    ],
  },
  {
    id: '2',
    userId: 'user2',
    name: 'Liam Sterling',
    role: 'Model',
    bio: 'Experienced male model specializing in commercial and fitness shoots. I bring energy and professionalism to every project.',
    profilePictureUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?q=80&w=600&h=800&auto=format&fit=crop',
    contactInfo: { email: 'liam@test.com' },
    height: "6'2\"",
    weight: "180 lbs",
    eyeColor: "Blue",
    hairColor: "Blonde",
    portfolio: [
      { id: 'p1', url: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?q=80&w=800&h=1200&auto=format&fit=crop', caption: 'City lights.' },
      { id: 'p2', url: 'https://images.unsplash.com/photo-1586083702768-190ae093d34d?q=80&w=800&h=1200&auto=format&fit=crop', caption: 'Active lifestyle.' },
      { id: 'p3', url: 'https://images.unsplash.com/photo-1521119989659-a83eee488004?q=80&w=800&h=1200&auto=format&fit=crop', caption: 'Sharp suit.' },
    ],
  },
    {
    id: '3',
    userId: 'user3',
    name: 'Aria Chen',
    role: 'Model',
    bio: 'An artist at heart, I use modeling as a medium for storytelling. My work explores themes of nature, identity, and tranquility.',
    profilePictureUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?q=80&w=600&h=800&auto=format&fit=crop',
    contactInfo: { email: 'aria@test.com', website: 'galleryoflight.dev/aria' },
    height: "5'7\"",
    weight: "118 lbs",
    eyeColor: "Brown",
    hairColor: "Black",
    portfolio: [
      { id: 'p1', url: 'https://images.unsplash.com/photo-1529949647969-1c8b05613303?q=80&w=800&h=1200&auto=format&fit=crop', caption: 'Forest spirit.' },
      { id: 'p2', url: 'https://images.unsplash.com/photo-1552339329-a1d2d4303496?q=80&w=800&h=1200&auto=format&fit=crop', caption: 'Reflections.' },
      { id: 'p3', url: 'https://images.unsplash.com/photo-1571513722247-4f659d431a4a?q=80&w=800&h=1200&auto=format&fit=crop', caption: 'Ethereal light.' },
      { id: 'p4', url: 'https://images.unsplash.com/photo-1575410291428-1b7598851722?q=80&w=800&h=1200&auto=format&fit=crop', caption: 'Wildflower field.' },
      { id: 'p5', url: 'https://images.unsplash.com/photo-1562572159-4efc207f5aff?q=80&w=800&h=1200&auto=format&fit=crop', caption: 'Coastal calm.' },
    ],
  },
   {
    id: '4',
    userId: 'user4',
    name: 'Mateo Rossi',
    role: 'Model',
    bio: 'With a strong, classic look, I specialize in high-fashion and editorial work. My goal is to create powerful and memorable images.',
    profilePictureUrl: 'https://images.unsplash.com/photo-1564564321837-a57b7070ac4f?q=80&w=600&h=800&auto=format&fit=crop',
    contactInfo: { email: 'mateo@test.com' },
    height: "6'1\"",
    weight: "175 lbs",
    eyeColor: "Green",
    hairColor: "Brown",
    portfolio: [
      { id: 'p1', url: 'https://images.unsplash.com/photo-1615109398623-88346a601842?q=80&w=800&h=1200&auto=format&fit=crop', caption: 'Sculpted form.' },
      { id: 'p2', url: 'https://images.unsplash.com/photo-1542206395-9feb3edaa68d?q=80&w=800&h=1200&auto=format&fit=crop', caption: 'Vintage vibes.' },
    ],
  },
  // Photographers
  {
    id: '5',
    userId: 'user5',
    name: 'Sienna Miller',
    role: 'Photographer',
    bio: 'I capture fleeting moments and turn them into timeless stories. My work focuses on portraiture and documentary photography, revealing the soul within the frame.',
    profilePictureUrl: 'https://images.unsplash.com/photo-1520466809213-7b9a56adcd45?q=80&w=600&h=800&auto=format&fit=crop',
    contactInfo: { email: 'sienna@test.com', website: 'siennamillerphoto.com' },
    height: "N/A",
    weight: "N/A",
    eyeColor: "N/A",
    hairColor: "N/A",
    portfolio: [
      { id: 'p1', url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=1200&h=800&auto=format&fit=crop', caption: 'The Writer.' },
      { id: 'p2', url: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?q=80&w=1200&h=800&auto=format&fit=crop', caption: 'Marketplace Hues.' },
      { id: 'p3', url: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?q=80&w=1200&h=800&auto=format&fit=crop', caption: 'Rainy Day in the City.' },
    ],
  },
  {
    id: '6',
    userId: 'user6',
    name: 'Julian Croft',
    role: 'Photographer',
    bio: 'Landscape and architectural photographer. I find beauty in structure, light, and the grand scale of nature.',
    profilePictureUrl: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?q=80&w=600&h=800&auto=format&fit=crop',
    contactInfo: { email: 'julian@test.com' },
    height: "N/A",
    weight: "N/A",
    eyeColor: "N/A",
    hairColor: "N/A",
    portfolio: [
      { id: 'p1', url: 'https://images.unsplash.com/photo-1477959858617-67f85cf4f1df?q=80&w=1200&h=800&auto=format&fit=crop', caption: 'Mountain Majesty.' },
      { id: 'p2', url: 'https://images.unsplash.com/photo-1444703686981-a3abbc4d4fe3?q=80&w=1200&h=800&auto=format&fit=crop', caption: 'Coastal Geometry.' },
    ],
  },
  // Makeup Artists
  {
    id: '7',
    userId: 'user7',
    name: 'Chloe Kim',
    role: 'Makeup Artist',
    bio: 'A makeup artist who believes in enhancing natural beauty. From clean, editorial looks to dramatic transformations, I paint faces with passion and precision.',
    profilePictureUrl: 'https://images.unsplash.com/photo-1557053910-d9eadeed1c58?q=80&w=600&h=800&auto=format&fit=crop',
    contactInfo: { email: 'chloe@test.com' },
    height: "N/A",
    weight: "N/A",
    eyeColor: "N/A",
    hairColor: "N/A",
    portfolio: [
      { id: 'p1', url: 'https://images.unsplash.com/photo-1608800974247-4d1566490354?q=80&w=800&h=1200&auto=format&fit=crop', caption: 'Golden Glow.' },
      { id: 'p2', url: 'https://images.unsplash.com/photo-1613926181934-1188507f3521?q=80&w=800&h=1200&auto=format&fit=crop', caption: 'Bold Liner.' },
      { id: 'p3', url: 'https://images.unsplash.com/photo-1596755531432-5eb72c918518?q=80&w=800&h=1200&auto=format&fit=crop', caption: 'Bridal Elegance.' },
    ],
  },
  // Artists
  {
    id: '8',
    userId: 'user8',
    name: 'Ren Ishikawa',
    role: 'Artist',
    bio: 'My work is a blend of traditional ink wash and digital illustration, exploring themes of mythology and the subconscious.',
    profilePictureUrl: 'https://images.unsplash.com/photo-1557862921-37829c790f19?q=80&w=600&h=800&auto=format&fit=crop',
    contactInfo: { email: 'ren@test.com' },
    height: "N/A",
    weight: "N/A",
    eyeColor: "N/A",
    hairColor: "N/A",
    portfolio: [
      { id: 'p1', url: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b6a5?q=80&w=1200&h=800&auto=format&fit=crop', caption: 'Dragon\'s Dream.' },
      { id: 'p2', url: 'https://images.unsplash.com/photo-1547891654-e66ed7ebb968?q=80&w=800&h=1200&auto=format&fit=crop', caption: 'Forest Spirit.' },
    ],
  },
];

export const MOCK_GIGS: Gig[] = [
  {
    id: 'gig1',
    title: 'E-commerce Fashion Shoot',
    description: 'Looking for a model for an upcoming e-commerce shoot for a new line of sustainable summer dresses. The shoot will take place outdoors in a natural setting. Must be comfortable with various poses and have a positive attitude. Please include a link to your portfolio in your application.',
    roleSought: 'Model',
    location: 'Pune, Maharashtra',
    date: '2024-08-15',
    payment: 'Paid - ₹15,000',
    postedByProfileId: '5',
    posterName: 'Sienna Miller',
    posterProfilePictureUrl: 'https://images.unsplash.com/photo-1520466809213-7b9a56adcd45?q=80&w=600&h=800&auto=format&fit=crop',
  },
  {
    id: 'gig2',
    title: 'Assistant for Architectural Photography',
    description: 'Seeking a second shooter and assistant for a 3-day architectural photography project in Mumbai. You will be responsible for lighting setup, equipment management, and capturing secondary shots. This is a great opportunity to learn from an experienced professional. A keen eye for detail is a must.',
    roleSought: 'Photographer',
    location: 'Mumbai, Maharashtra',
    date: '2024-09-01',
    payment: 'Paid - ₹25,000 for 3 days',
    postedByProfileId: '6',
    posterName: 'Julian Croft',
    posterProfilePictureUrl: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?q=80&w=600&h=800&auto=format&fit=crop',
  },
    {
    id: 'gig3',
    title: 'TFP Collaboration: Ethereal Forest Theme',
    description: 'I\'m a model looking to collaborate with a photographer and a makeup artist on a TFP (Time for Prints) basis. The theme is "Ethereal Forest Spirit". I have a specific location in Lonavala in mind. Let\'s create some magic together! Moodboard will be shared upon application.',
    roleSought: 'Photographer',
    location: 'Lonavala, Maharashtra',
    date: 'Flexible',
    payment: 'TFP/Collaboration',
    postedByProfileId: '3',
    posterName: 'Aria Chen',
    posterProfilePictureUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?q=80&w=600&h=800&auto=format&fit=crop',
  },
   {
    id: 'gig4',
    title: 'Bridal Makeup Artist for Wedding',
    description: 'We are looking for a skilled makeup artist for a bride and three bridesmaids for a wedding ceremony in Nashik. The ideal candidate should have experience with bridal makeup and be able to create a long-lasting, natural, and radiant look. Please provide a portfolio of your previous bridal work.',
    roleSought: 'Makeup Artist',
    location: 'Nashik, Maharashtra',
    date: '2024-11-22',
    payment: 'Paid - ₹20,000',
    postedByProfileId: '5',
    posterName: 'Sienna Miller',
    posterProfilePictureUrl: 'https://images.unsplash.com/photo-1520466809213-7b9a56adcd45?q=80&w=600&h=800&auto=format&fit=crop',
  },
];

export const MOCK_REVIEWS: Review[] = [
    {
        id: 'review1',
        gigId: 'gig1',
        reviewerProfileId: '5', // Sienna Miller (Photographer)
        reviewerName: 'Sienna Miller',
        reviewerProfilePictureUrl: 'https://images.unsplash.com/photo-1520466809213-7b9a56adcd45?q=80&w=600&h=800&auto=format&fit=crop',
        revieweeProfileId: '1', // Elara Vance (Model)
        rating: 5,
        comment: 'Elara was an absolute professional. She brought great energy to the set and took direction perfectly. The final shots are stunning. Highly recommend!',
        createdAt: '2024-08-16T10:00:00Z',
    },
    {
        id: 'review2',
        gigId: 'gig-completed-1', // A hypothetical completed gig
        reviewerProfileId: '2', // Liam Sterling (Model)
        reviewerName: 'Liam Sterling',
        reviewerProfilePictureUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?q=80&w=600&h=800&auto=format&fit=crop',
        revieweeProfileId: '6', // Julian Croft (Photographer)
        rating: 5,
        comment: 'Julian is a master of light and composition. He made the entire process seamless and fun, and the results speak for themselves. A true artist.',
        createdAt: '2024-07-20T14:30:00Z',
    },
    {
        id: 'review3',
        gigId: 'gig-completed-2',
        reviewerProfileId: '3', // Aria Chen (Model)
        reviewerName: 'Aria Chen',
        reviewerProfilePictureUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?q=80&w=600&h=800&auto=format&fit=crop',
        revieweeProfileId: '5', // Sienna Miller (Photographer)
        rating: 5,
        comment: 'Working with Sienna was a dream. She has a unique ability to capture emotion and tell a story with her camera. I\'m so proud of the work we created together.',
        createdAt: '2024-06-05T18:00:00Z',
    },
    {
        id: 'review4',
        gigId: 'gig-completed-3',
        reviewerProfileId: '7', // Chloe Kim (MUA)
        reviewerName: 'Chloe Kim',
        reviewerProfilePictureUrl: 'https://images.unsplash.com/photo-1557053910-d9eadeed1c58?q=80&w=600&h=800&auto=format&fit=crop',
        revieweeProfileId: '1', // Elara Vance (Model)
        rating: 4,
        comment: 'Elara has a fantastic look and is very patient in the makeup chair. A pleasure to work with!',
        createdAt: '2024-05-11T12:00:00Z',
    }
];